title: Amirul Affiq</p>
logo: 'https://amrlaffq.github.io/images/profile pic.png'
description: A graduate from Data Star program by CADS who enthusiasm in data science and love performing data analysis. Really looking forward to be working with experienced team where could learn much more in data science.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
